### ISSUE TITLE
Bug: custom extractor, Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by samislam** [tolgee/tolgee-cli#112]
I am running this command and getting an error:
```
$ tolgee extract print                                                                                                                                                             21:52:44
🐭✅     Analyzing code...
1 key found in src/utils/getUserLocale.ts:
	line 1: hi
🔴 An unexpected error occurred while running the command.
🔴 Please report this to our issue tracker: https://github.com/tolgee/tolgee-cli/issues
🔴 Cannot read properties of undefined (reading 'length')
```

This is the very simple and minimum extractor code:
```js
module.exports = function extrator(code) {
  return {
    keys: [{ keyName: 'hi', line: 1 }],
  }
}
```
And here is my .tolgeerc file
```
{
  "$schema": "https://tolgee.io/cli-schema.json",
  "apiUrl": "https://app.tolgee.io",
  "projectId": 9898,
  "format": "JSON_TOLGEE",
  "patterns": ["./src/**/*.ts?(x)"],
  "push": {
    "files": [
      {
        "path": "./src/i18n/en.json",
        "language": "en"
      },
      {
        "path": "./src/i18n/ar.json",
        "language": "ar"
      }
    ],
    "forceMode": "OVERRIDE"
  },
  "pull": {
    "path": "./src/i18n"
  },
  "extractor": "./src/config/tolgee/tolgee-extractor.cjs"
}

```

**Comment by samislam** [comment]
I re-ran the command with verbose mode:
```
╰─>$ tolgee extract print -v                                                                                                                                                          22:09:19
🐭✅     Analyzing code...
🔴 An unexpected error occurred while running the command.
🔴 Please report this to our issue tracker: https://github.com/tolgee/tolgee-cli/issues
🔴 Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at Command.<anonymous> (file:///home/sam/.local/share/pnpm/global/5/.pnpm/@tolgee+cli@2.1.6_typescript@5.3.3/node_modules/@tolgee/cli/dist/commands/extract/print.js:26:22)
    at async Command.parseAsync (/home/sam/.local/share/pnpm/global/5/.pnpm/commander@12.1.0/node_modules/commander/lib/command.js:1092:5)
    at async run (file:///home/sam/.local/share/pnpm/global/5/.pnpm/@tolgee+cli@2.1.6_typescript@5.3.3/node_modules/@tolgee/cli/dist/cli.js:128:9)
┬─[sam@sam:~/D/p/s/sham-portal]─[10:09:19 PM]─[G:v1-dev>]
╰─>$
```

**Comment by samislam** [comment]
I re-ran the command with verbose mode:
```
╰─>$ tolgee extract print -v                                                                                                                                                          22:09:19
🐭✅     Analyzing code...
🔴 An unexpected error occurred while running the command.
🔴 Please report this to our issue tracker: https://github.com/tolgee/tolgee-cli/issues
🔴 Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at Command.<anonymous> (file:///~/.local/share/pnpm/global/5/.pnpm/@tolgee+cli@2.1.6_typescript@5.3.3/node_modules/@tolgee/cli/dist/commands/extract/print.js:26:22)
    at async Command.parseAsync (/~/.local/share/pnpm/global/5/.pnpm/commander@12.1.0/node_modules/commander/lib/command.js:1092:5)
    at async run (file:///~/.local/share/pnpm/global/5/.pnpm/@tolgee+cli@2.1.6_typescript@5.3.3/node_modules/@tolgee/cli/dist/cli.js:128:9)
┬─[~@~:~/D/p/s/sham-portal]─[10:09:19 PM]─[G:v1-dev>]
╰─>$
```

**Comment by samislam** [comment]
I solved the issue by adding the `warnings: []` property in the return object.
This is still a bug because in the documentation [here](https://tolgee.io/tolgee-cli/extraction/custom-extractor#type-definitions), it says that the warning property is optional

```diff
module.exports = function extrator(code) {
  return {
    keys: [{ keyName: 'hi', line: 1 }],
+   warnings: []
  }
}

**Comment by stepan662** [comment]
Yep, there for some reason there was inconsistency between docs and code. I've fixed it in the code.
