### ISSUE TITLE
Most of the time receive an error while pushing to tolgee

### ISSUE THREAD

**Issue by rynhevich** [tolgee/tolgee-cli#117]
We started to receive this error a few days ago. Usually, it finally went through after rerunning it for a couple of times, but today even this doesn't help.

Version of tolgee/cli - 2.1.6. We tried to upgrade to 2.2.0, but nothing has changed.

```
🐭✅     Reading files...
⚪ [HTTP] Requesting: POST https://app.tolgee.io/v2/projects/2982/single-step-import
🐁       Importing...⚪ [HTTP] Response: https://app.tolgee.io/v2/projects/2982/single-step-import [504]
🐭✅     Uploading files...
🐭✅     Importing...
🔴 Unknown error [status: 504]
    at handleLoadableError (file:///Users/rynhevich/Library/pnpm/global/5/.pnpm/@tolgee+cli@2.1.6/node_modules/@tolgee/cli/dist/client/TolgeeClient.js:16:9)
    at Command.<anonymous> (file:///Users/rynhevich/Library/pnpm/global/5/.pnpm/@tolgee+cli@2.1.6/node_modules/@tolgee/cli/dist/commands/push.js:115:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (/Users/rynhevich/Library/pnpm/global/5/.pnpm/commander@12.1.0/node_modules/commander/lib/command.js:1092:5)
    at async run (file:///Users/vadzim/Library/pnpm/global/5/.pnpm/@tolgee+cli@2.1.6/node_modules/@tolgee/cli/dist/cli.js:128:9)
failed to wait for command termination: exit status 1
```

**Comment by JanCizmar** [comment]
Can you please share the data you are importing? It looks like something takes too long. You can do so via DMing me via our slack community channel: https://tolg.ee/slack
