### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by vinnyglennon** [tolgee/tolgee-cli#76]
Hosting Tolgee on https://redacted_personal_url 
Project id: 2
installed via: npm i --global @tolgee/cli

tolgee --api-url https://redacted_personal_url  --project-id 2 --api-key tgpak_redacted_key pull config/locales/

gives

🟡 The specified path /Users/redacted/src/redacted/config/locales already exists.
Do you want to overwrite data? *BE CAREFUL, ALL THE CONTENTS OF THE DESTINATION FOLDER WILL BE DESTROYED*. [y/N] y
⚪ [HTTP] Requesting: POST https://redacted_personal_url/v2/projects/2/export
⚪ [HTTP] POST https://redacted_personal_url/v2/projects/2/export -> 302 Found
🐭✅     Fetching strings from Tolgee...
🐭🔴     Extracting strings...
🔴 An unexpected error occurred while running the command.
🔴 Please report this to our issue tracker: https://github.com/tolgee/tolgee-cli/issues
Error: end of central directory record signature not found
    at /opt/homebrew/lib/node_modules/@tolgee/cli/node_modules/yauzl/index.js:187:14
    at Immediate.<anonymous> (/opt/homebrew/lib/node_modules/@tolgee/cli/node_modules/yauzl/index.js:624:38)
    at process.processImmediate (node:internal/timers:478:21)

**Comment by cyyynthia** [comment]
This 302 redirect is probably what's causing the issue. The CLI doesn't expect redirects which means it's trying to decompress the empty response it got with the redirect.

Is the redirect caused by your configuration (reverse proxy, ...) or is it from Tolgee itself?
